# Generated by Django 3.2.5 on 2022-02-08 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmscontexts', '0011_alter_webpath_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unicms_newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterWebpath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletterwebpath_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletterwebpath_modified_by', to=settings.AUTH_USER_MODEL)),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicms_newsletter.newsletter')),
                ('webpath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmscontexts.webpath')),
            ],
            options={
                'unique_together': {('newsletter', 'webpath')},
            },
        ),
    ]
