# Generated by Django 3.2.5 on 2022-02-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0003_auto_20220209_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='intro_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
