# Generated by Django 3.2.5 on 2022-02-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0004_alter_message_intro_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagesending',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='messagesending',
            name='failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messagesending',
            name='success',
            field=models.IntegerField(default=0),
        ),
    ]
