# Generated by Django 3.2.5 on 2022-02-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0005_auto_20220209_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='days_interval',
            new_name='repeat_each',
        ),
    ]
