# Generated by Django 3.2.5 on 2022-02-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0006_rename_days_interval_message_repeat_each'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='repeat_each',
            field=models.IntegerField(default=0, help_text='in days'),
        ),
    ]
