# Generated by Django 3.2.5 on 2022-02-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0007_alter_message_repeat_each'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscription',
            name='date_subscription',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
