# Generated by Django 3.2.5 on 2022-02-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0008_alter_newslettersubscription_date_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
