# Generated by Django 3.2.5 on 2022-02-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscontexts', '0011_alter_webpath_options'),
        ('unicms_newsletter', '0009_alter_newsletter_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='newsletter',
            unique_together={('slug', 'site')},
        ),
    ]
