# Generated by Django 3.2.5 on 2022-02-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0010_auto_20220211_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscription',
            name='date_subscription',
            field=models.DateTimeField(),
        ),
    ]
