# Generated by Django 3.2.5 on 2022-02-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0012_alter_newslettersubscription_date_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscription',
            name='date_subscription',
            field=models.DateTimeField(),
        ),
    ]
