# Generated by Django 3.2.5 on 2022-02-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0013_alter_newslettersubscription_date_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='modified_by',
        ),
    ]
