# Generated by Django 3.2.5 on 2022-02-14 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0014_auto_20220214_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='created',
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='modified',
        ),
    ]
