# Generated by Django 3.2.5 on 2022-02-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0015_auto_20220214_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesending',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='messagesending',
            name='modified_by',
        ),
    ]
