# Generated by Django 3.2.5 on 2022-02-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0016_auto_20220216_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagepublicationcategories',
            name='order',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
