# Generated by Django 3.2.5 on 2022-02-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0018_messagesending_html_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesending',
            name='html_content',
        ),
        migrations.RemoveField(
            model_name='messagesending',
            name='text_content',
        ),
    ]
