# Generated by Django 3.2.5 on 2022-02-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0019_auto_20220218_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesending',
            name='html_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
