# Generated by Django 3.2.5 on 2022-04-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0022_message_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='footer_text',
            field=models.TextField(default='', null=True),
        ),
    ]
