# Generated by Django 3.2.5 on 2022-04-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0025_auto_20220422_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageattachment',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='messagepublication',
            options={'ordering': ('order', 'publication__publication__title')},
        ),
        migrations.AlterModelOptions(
            name='messagepublicationcategories',
            options={'ordering': ('order', 'category__name')},
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='order',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='messagepublication',
            name='order',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
