# Generated by Django 3.2.5 on 2022-04-22 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0027_alter_messagewebpath_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterTestSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('html', models.BooleanField(default=True)),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicms_newsletter.newsletter')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('newsletter', 'email')},
            },
        ),
    ]
