# Generated by Django 3.2.5 on 2022-04-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0029_auto_20220422_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='message',
            name='template',
            field=models.CharField(blank=True, default='newsletter/body.html', max_length=254),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
