# Generated by Django 3.2.5 on 2022-04-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0031_alter_message_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='banner_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
