# Generated by Django 3.2.5 on 2022-04-28 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmspublications', '0022_auto_20220128_1536'),
        ('unicms_newsletter', '0034_messagepublication'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagePublicationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(blank=True, default=10, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmspublications.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messagepublicationcategory_created_by', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicms_newsletter.message')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messagepublicationcategory_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('order', 'category__name'),
                'unique_together': {('message', 'category')},
            },
        ),
        migrations.DeleteModel(
            name='MessagePublicationCategories',
        ),
    ]
