# Generated by Django 3.2.5 on 2022-04-29 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unicms_newsletter', '0035_auto_20220428_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newslettersubscription_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newslettersubscription_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newslettertestsubscription',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newslettertestsubscription_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newslettertestsubscription',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newslettertestsubscription_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
