# Generated by Django 3.2.5 on 2022-05-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0037_auto_20220502_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='repeat_each',
            field=models.PositiveIntegerField(default=0, help_text='in days'),
        ),
    ]
