# Generated by Django 3.2.5 on 2022-05-02 11:14

import cms.medias.validators
from django.db import migrations, models
import unicms_newsletter.models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0038_alter_message_repeat_each'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='attachment',
            field=models.FileField(upload_to=unicms_newsletter.models.message_attachment_path, validators=[cms.medias.validators.validate_file_extension, cms.medias.validators.validate_file_size]),
        ),
    ]
