# Generated by Django 3.2.5 on 2022-05-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0039_alter_messageattachment_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='conditions',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
    ]
