# Generated by Django 3.2.5 on 2022-05-09 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0041_message_sending'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hour',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)]),
        ),
    ]
