# Generated by Django 3.2.5 on 2022-05-09 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0042_message_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='hour',
            field=models.IntegerField(blank=True, help_text='The sending time value, 0-23 (depends on the cronjob setting)', null=True, validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)]),
        ),
    ]
