# Generated by Django 3.2.5 on 2022-05-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0043_alter_message_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='is_subscritable',
            field=models.BooleanField(default=False),
        ),
    ]
