# Generated by Django 3.2.5 on 2022-05-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0044_newsletter_is_subscritable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='is_subscritable',
            new_name='is_subscpritable',
        ),
    ]
