# Generated by Django 3.2.5 on 2022-05-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0046_rename_is_subscpritable_newsletter_is_subscriptable'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
