# Generated by Django 3.2.5 on 2022-05-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0047_newsletter_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='is_subscriptable',
            field=models.BooleanField(default=True),
        ),
    ]
