# Generated by Django 3.2.5 on 2022-05-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0048_alter_newsletter_is_subscriptable'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='week_day',
            field=models.CharField(default=[1, 2], max_length=20),
            preserve_default=False,
        ),
    ]
