# Generated by Django 3.2.5 on 2022-05-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0049_message_week_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='week_day',
            field=models.CharField(default='0,1,2,3,4,5,6', max_length=20),
        ),
    ]
