# Generated by Django 3.2.5 on 2022-05-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0050_alter_message_week_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='week_day',
            field=models.CharField(max_length=20),
        ),
    ]
