# Generated by Django 3.2.5 on 2022-05-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0051_alter_message_week_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='repeat_each',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='in days'),
        ),
        migrations.AlterField(
            model_name='message',
            name='week_day',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
