# Generated by Django 3.2.5 on 2022-05-13 08:03

import cms.medias.validators
from django.db import migrations, models
import unicms_newsletter.models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0053_auto_20220511_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=unicms_newsletter.models.message_banner_path, validators=[cms.medias.validators.validate_file_size]),
        ),
    ]
