# Generated by Django 3.2.5 on 2022-05-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0054_alter_message_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='week_day',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
