# Generated by Django 3.2.5 on 2022-05-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0055_alter_message_week_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='sender_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
