# Generated by Django 3.2.13 on 2022-05-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0057_alter_newsletter_sender_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='repeat_each',
            field=models.PositiveIntegerField(blank=True, help_text='in days', null=True),
        ),
    ]
