# Generated by Django 3.2.13 on 2022-06-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_newsletter', '0058_alter_message_repeat_each'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagewebpath',
            name='news_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagewebpath',
            name='news_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
