# Generated by Django 4.2.5 on 2023-10-05 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "unicms_calendar",
            "0012_alter_calendar_created_by_alter_calendar_modified_by_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "unicms_newsletter",
            "0064_alter_message_created_by_alter_message_modified_by_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageCalendarContext",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                ("events_from", models.DateTimeField(blank=True, null=True)),
                ("events_to", models.DateTimeField(blank=True, null=True)),
                (
                    "calendar_context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="unicms_calendar.calendarcontext",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="unicms_newsletter.message",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("calendar_context",),
                "unique_together": {("message", "calendar_context")},
            },
        ),
    ]
