# Generated by Django 4.2.7 on 2023-11-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("unicms_newsletter", "0065_messagecalendarcontext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="message",
            name="template",
            field=models.CharField(
                blank=True, default="", help_text="newsletter/body.html", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="week_day",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="newslettersubscription",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="newslettersubscription",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="newslettertestsubscription",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="newslettertestsubscription",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
