CMS_NEWSLETTER_LIST_PREFIX_PATH = 'contents/newsletters/list'
CMS_NEWSLETTER_VIEW_PREFIX_PATH = 'contents/newsletters/view'
CMS_NEWSLETTER_MESSAGE_SUB_PATH = 'message'
CMS_NEWSLETTER_MESSAGE_SENDING_SUB_PATH = 'sending'

CMS_NEWSLETTER_URL_LIST_REGEXP = f'^(/)({CMS_NEWSLETTER_LIST_PREFIX_PATH})(/)?$'
CMS_NEWSLETTER_URL_VIEW_REGEXP = f'^(/)({CMS_NEWSLETTER_VIEW_PREFIX_PATH})/(?P<slug>[a-zA-Z0-9\-\_]*)(/)?$'
CMS_NEWSLETTER_MESSAGE_URL_VIEW_REGEXP = f'^(/)({CMS_NEWSLETTER_VIEW_PREFIX_PATH})/(?P<newsletter_id>[a-zA-Z0-9\-\_]*)/{CMS_NEWSLETTER_MESSAGE_SUB_PATH}/(?P<code>[0-9]*)(/)?$'
CMS_NEWSLETTER_MESSAGE_SENDING_URL_VIEW_REGEXP = f'^(/)({CMS_NEWSLETTER_VIEW_PREFIX_PATH})/(?P<newsletter_id>[a-zA-Z0-9\-\_]*)/{CMS_NEWSLETTER_MESSAGE_SUB_PATH}/(?P<message_id>[0-9]*)/{CMS_NEWSLETTER_MESSAGE_SENDING_SUB_PATH}/(?P<code>[0-9]*)(/)?$'

CMS_NEWSLETTER_HANDLERS_PATHS = [
    CMS_NEWSLETTER_URL_LIST_REGEXP,
    CMS_NEWSLETTER_URL_VIEW_REGEXP,
    CMS_NEWSLETTER_MESSAGE_URL_VIEW_REGEXP,
    CMS_NEWSLETTER_MESSAGE_SENDING_URL_VIEW_REGEXP
]

CMS_NEWSLETTER_APP_REGEXP_URLPATHS = {
    'unicms_newsletter.handlers.NewsletterListHandler': CMS_NEWSLETTER_URL_LIST_REGEXP,
    'unicms_newsletter.handlers.NewsletterViewHandler': CMS_NEWSLETTER_URL_VIEW_REGEXP,
    'unicms_newsletter.handlers.NewsletterMessageViewHandler': CMS_NEWSLETTER_MESSAGE_URL_VIEW_REGEXP,
    'unicms_newsletter.handlers.NewsletterMessageSendingViewHandler': CMS_NEWSLETTER_MESSAGE_SENDING_URL_VIEW_REGEXP,
}

NEWSLETTER_MAX_ITEMS_IN_CATEGORY = 5
NEWSLETTER_MAX_FREE_ITEMS = 15

NEWSLETTER_SEND_EMAIL_GROUP = 10
NEWSLETTER_SEND_EMAIL_GROUP_DELAY = 5
NEWSLETTER_SEND_EMAIL_DELAY = 0

DEFAULT_TEMPLATE = 'newsletter/body.html'

TOKEN_EXPIRATION = 30 # days
